# Generated by Django 5.2.7 on 2025-10-14 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Lawn & Gardening', 'Lawn & Gardening'), ('Hand Tools', 'Hand Tools'), ('Earth Auger', 'Earth Auger'), ('Ploughs', 'Ploughs'), ('Seeders', 'Seeders'), ('Sprayers', 'Sprayers'), ('Fertilizers', 'Fertilizers'), ('Tools', 'Tools')], max_length=50)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agriculture_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
