# Generated by Django 5.2.7 on 2025-10-14 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_agricultureitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureitem',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agricultureitem',
            name='category',
            field=models.CharField(choices=[('Lawn & Gardening', 'Lawn & Gardening'), ('Hand Tools', 'Hand Tools'), ('Earth Auger', 'Earth Auger'), ('Ploughs', 'Ploughs'), ('Seeders', 'Seeders'), ('Sprayers', 'Sprayers'), ('Fertilizers', 'Fertilizers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agricultureitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='agricultureitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agricultureitem',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
