# Generated by Django 5.2.7 on 2025-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_agricultureitem_status_customuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='damage_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='pending', max_length=10),
        ),
    ]
