# Generated by Django 5.2.7 on 2025-10-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rentalrequest_advance_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'ordering': ['-request_date']},
        ),
    ]
