# Generated by Django 5.2.7 on 2025-10-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rentalrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agricultureitem',
            name='status',
        ),
    ]
