# Generated by Django 5.2.7 on 2025-10-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_agricultureitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
