# Generated by Django 5.2.7 on 2025-11-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_aadhaar_back_customuser_aadhaar_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='admin_return_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('damaged', 'Damaged')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='return_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
