# Generated by Django 5.2.7 on 2025-11-07 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agricultureitem',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agricultureitem',
            name='new_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agricultureitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
